### ISSUE TITLE
Synchronization issues when trying to increment progress bar

### ISSUE THREAD

**Issue by alalessi** [panamax-rs/panamax#9]
I followed the instructions in readme.md, and the first sync job resulted in a panic:

```
[1/5] Syncing rustup-init files... █████████████████████████████████████████████████████████████████████████████████████████████████ 27/27 [00:00:40]
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
Downloading . failed: Io(Custom { kind: Other, error: Error(Hyper(Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))) })
[2/5] Syncing latest stable...     ███████████████████████████████████████████████████████████████████████████████████████████████ 626/626 [00:58:31]
thread '<unnamed>' panicked at 'Channel send should not fail: "SendError(..)"', /home/alalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/panamax-0.2.0/src/rustup.rs:454:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Channel send should not fail: "SendError(..)"', /home/alalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/panamax-0.2.0/src/rustup.rs:454:17
thread '<unnamed>' panicked at 'Channel send should not fail: "SendError(..)"', /home/alalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/panamax-0.2.0/src/rustup.rs:454:17
thread '<unnamed>' panicked at 'Channel send should not fail: "SendError(..)"', /home/alalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/panamax-0.2.0/src/rustup.rs:454:17
thread 'main' panicked at 'Thread pool worker panicked', /home/alalassi/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:236:13
```

I did rerun the job with `RUST_BACKTRACE=1` environment variable set, but it did not reproduce the bug. 

I guess the Sender created in `progress_bar.rs` was deallocated before the last `ProgressBarMessage::Increment` was sent ([see std::sync::mpsc docs](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html#method.send)).

**Comment by k3d3** [comment]
Yep, that makes sense. I'll see what I can do to reproduce this - I can imagine it being pretty annoying dealing with a heisenbug like this.

Thanks for the report!

**Comment by k3d3** [comment]
Unfortunately I've yet to be able to reproduce this. I'm going to close it for now, but please feel free to re-open if you experience it again.

Thanks!
